import {
  Contact, Account, Deal, Activity, Lead, Case,
  CallScript, Campaign, Product, Org, User, Integration,
  type DealStage, type ActivityStatus, type ActivityType,
  type LeadStatus, type CasePriority, type CaseStatus,
} from "./types";

// ── Orgs ──
export const orgs: Org[] = [
  { id: "org-1", name: "Acme Corp", timezone: "America/New_York", fiscalYear: "January" },
  { id: "org-2", name: "TechStart Inc", timezone: "America/Los_Angeles", fiscalYear: "April" },
  { id: "org-3", name: "Global Finance", timezone: "Europe/London", fiscalYear: "January" },
];

// ── Users ──
export const users: User[] = [
  { id: "1", name: "Demo User", email: "demo@axia.crm", role: "admin", orgId: "org-1", orgName: "Acme Corp" },
  { id: "2", name: "Sarah Chen", email: "sarah@axia.crm", role: "manager", orgId: "org-1", orgName: "Acme Corp" },
  { id: "3", name: "Mike Johnson", email: "mike@axia.crm", role: "rep", orgId: "org-1", orgName: "Acme Corp" },
  { id: "4", name: "Emily Davis", email: "emily@axia.crm", role: "rep", orgId: "org-1", orgName: "Acme Corp" },
  { id: "5", name: "Alex Kim", email: "alex@axia.crm", role: "admin", orgId: "org-2", orgName: "TechStart Inc" },
  { id: "6", name: "Lisa Park", email: "lisa@axia.crm", role: "rep", orgId: "org-2", orgName: "TechStart Inc" },
  { id: "7", name: "James Wilson", email: "james@axia.crm", role: "admin", orgId: "org-3", orgName: "Global Finance" },
  { id: "8", name: "Rachel Brown", email: "rachel@axia.crm", role: "manager", orgId: "org-3", orgName: "Global Finance" },
];

// ── Contacts ──
export const contacts: Contact[] = [
  { id: "c1", firstName: "John", lastName: "Smith", title: "VP of Sales", accountId: "a1", accountName: "Globex Corporation", phone: "(555) 123-4567", mobile: "(555) 987-6543", email: "john.smith@globex.com", mailingAddress: "123 Main St, Springfield, IL 62701", department: "Sales", description: "Key decision maker for enterprise accounts", ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-09-15", updatedAt: "2025-12-01" },
  { id: "c2", firstName: "Jane", lastName: "Doe", title: "CTO", accountId: "a2", accountName: "Initech", phone: "(555) 234-5678", email: "jane.doe@initech.com", mailingAddress: "456 Oak Ave, Austin, TX 73301", department: "Engineering", description: "Technical buyer, evaluates all software purchases", ownerId: "2", ownerName: "Sarah Chen", orgId: "org-1", createdAt: "2025-08-20", updatedAt: "2025-11-15" },
  { id: "c3", firstName: "Robert", lastName: "Brown", title: "Director of Marketing", accountId: "a3", accountName: "Umbrella Corp", phone: "(555) 345-6789", email: "rbrown@umbrella.com", mailingAddress: "789 Pine Rd, Raccoon City, OH 44101", department: "Marketing", ownerId: "3", ownerName: "Mike Johnson", orgId: "org-1", createdAt: "2025-07-10", updatedAt: "2025-10-22" },
  { id: "c4", firstName: "Maria", lastName: "Garcia", title: "CEO", accountId: "a4", accountName: "Stark Industries", phone: "(555) 456-7890", mobile: "(555) 111-2222", email: "mgarcia@stark.com", mailingAddress: "1 Stark Tower, New York, NY 10001", department: "Executive", description: "Final approver for all deals over $100K", ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-06-05", updatedAt: "2025-12-10" },
  { id: "c5", firstName: "David", lastName: "Lee", title: "Head of Procurement", accountId: "a5", accountName: "Wayne Enterprises", phone: "(555) 567-8901", email: "dlee@wayne.com", mailingAddress: "1007 Mountain Dr, Gotham, NJ 07001", department: "Procurement", ownerId: "2", ownerName: "Sarah Chen", orgId: "org-1", createdAt: "2025-05-18", updatedAt: "2025-11-30" },
  { id: "c6", firstName: "Lisa", lastName: "Wang", title: "VP Engineering", accountId: "a1", accountName: "Globex Corporation", phone: "(555) 678-9012", email: "lwang@globex.com", mailingAddress: "123 Main St, Springfield, IL 62701", department: "Engineering", ownerId: "3", ownerName: "Mike Johnson", orgId: "org-1", createdAt: "2025-10-01", updatedAt: "2025-12-05" },
  { id: "c7", firstName: "James", lastName: "Taylor", title: "Sales Manager", accountId: "a2", accountName: "Initech", phone: "(555) 789-0123", email: "jtaylor@initech.com", mailingAddress: "456 Oak Ave, Austin, TX 73301", department: "Sales", ownerId: "4", ownerName: "Emily Davis", orgId: "org-1", createdAt: "2025-09-22", updatedAt: "2025-11-28" },
  { id: "c8", firstName: "Emma", lastName: "Wilson", title: "CFO", accountId: "a3", accountName: "Umbrella Corp", phone: "(555) 890-1234", email: "ewilson@umbrella.com", mailingAddress: "789 Pine Rd, Raccoon City, OH 44101", department: "Finance", ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-08-11", updatedAt: "2025-12-02" },
  { id: "c9", firstName: "Michael", lastName: "Chen", title: "Product Manager", accountId: "a6", accountName: "Acme Solutions", phone: "(555) 901-2345", email: "mchen@acmesol.com", mailingAddress: "321 Elm St, San Francisco, CA 94102", department: "Product", ownerId: "2", ownerName: "Sarah Chen", orgId: "org-1", createdAt: "2025-07-15", updatedAt: "2025-11-20" },
  { id: "c10", firstName: "Sarah", lastName: "Johnson", title: "Director of IT", accountId: "a7", accountName: "Cyberdyne Systems", phone: "(555) 012-3456", email: "sjohnson@cyberdyne.com", mailingAddress: "18144 El Camino Real, Sunnyvale, CA 94087", department: "IT", ownerId: "3", ownerName: "Mike Johnson", orgId: "org-1", createdAt: "2025-06-28", updatedAt: "2025-10-15" },
  { id: "c11", firstName: "Tom", lastName: "Anderson", title: "VP Sales", accountId: "a8", accountName: "Soylent Corp", phone: "(555) 111-3333", email: "tanderson@soylent.com", mailingAddress: "500 Broadway, New York, NY 10012", department: "Sales", ownerId: "4", ownerName: "Emily Davis", orgId: "org-1", createdAt: "2025-10-05", updatedAt: "2025-12-08" },
  { id: "c12", firstName: "Amy", lastName: "Rodriguez", title: "Marketing Director", accountId: "a4", accountName: "Stark Industries", phone: "(555) 222-4444", email: "arodriguez@stark.com", mailingAddress: "1 Stark Tower, New York, NY 10001", department: "Marketing", ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-09-12", updatedAt: "2025-11-25" },
  { id: "c13", firstName: "Kevin", lastName: "Patel", title: "CIO", accountId: "a5", accountName: "Wayne Enterprises", phone: "(555) 333-5555", email: "kpatel@wayne.com", mailingAddress: "1007 Mountain Dr, Gotham, NJ 07001", department: "IT", ownerId: "2", ownerName: "Sarah Chen", orgId: "org-1", createdAt: "2025-08-30", updatedAt: "2025-12-12" },
  { id: "c14", firstName: "Nicole", lastName: "Kim", title: "Account Executive", accountId: "a6", accountName: "Acme Solutions", phone: "(555) 444-6666", email: "nkim@acmesol.com", mailingAddress: "321 Elm St, San Francisco, CA 94102", department: "Sales", ownerId: "3", ownerName: "Mike Johnson", orgId: "org-1", createdAt: "2025-07-22", updatedAt: "2025-10-30" },
  { id: "c15", firstName: "Brian", lastName: "Murphy", title: "Head of Sales", accountId: "a7", accountName: "Cyberdyne Systems", phone: "(555) 555-7777", email: "bmurphy@cyberdyne.com", mailingAddress: "18144 El Camino Real, Sunnyvale, CA 94087", department: "Sales", ownerId: "4", ownerName: "Emily Davis", orgId: "org-1", createdAt: "2025-06-15", updatedAt: "2025-11-10" },
  { id: "c16", firstName: "Rachel", lastName: "Foster", title: "Operations Manager", accountId: "a8", accountName: "Soylent Corp", phone: "(555) 666-8888", email: "rfoster@soylent.com", mailingAddress: "500 Broadway, New York, NY 10012", department: "Operations", ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-10-18", updatedAt: "2025-12-15" },
  { id: "c17", firstName: "Daniel", lastName: "Wright", title: "VP Product", accountId: "a9", accountName: "Weyland-Yutani", phone: "(555) 777-9999", email: "dwright@weyland.com", mailingAddress: "900 Industrial Pkwy, Houston, TX 77001", department: "Product", ownerId: "2", ownerName: "Sarah Chen", orgId: "org-1", createdAt: "2025-09-05", updatedAt: "2025-11-22" },
  { id: "c18", firstName: "Laura", lastName: "Martinez", title: "Director of HR", accountId: "a10", accountName: "Oscorp Industries", phone: "(555) 888-0000", email: "lmartinez@oscorp.com", mailingAddress: "200 Park Ave, New York, NY 10166", department: "HR", ownerId: "3", ownerName: "Mike Johnson", orgId: "org-1", createdAt: "2025-08-02", updatedAt: "2025-10-28" },
  { id: "c19", firstName: "Chris", lastName: "Evans", title: "Sales Director", accountId: "a9", accountName: "Weyland-Yutani", phone: "(555) 999-1111", email: "cevans@weyland.com", mailingAddress: "900 Industrial Pkwy, Houston, TX 77001", department: "Sales", ownerId: "4", ownerName: "Emily Davis", orgId: "org-1", createdAt: "2025-07-28", updatedAt: "2025-12-01" },
  { id: "c20", firstName: "Sophie", lastName: "Turner", title: "Chief Revenue Officer", accountId: "a10", accountName: "Oscorp Industries", phone: "(555) 000-2222", email: "sturner@oscorp.com", mailingAddress: "200 Park Ave, New York, NY 10166", department: "Revenue", ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-06-20", updatedAt: "2025-11-18" },
  // Org 2
  { id: "c21", firstName: "Alex", lastName: "Kim", title: "Sales Rep", accountId: "a11", accountName: "CloudFirst", phone: "(555) 100-2000", email: "akim@cloudfirst.com", mailingAddress: "100 Cloud Way, Seattle, WA 98101", department: "Sales", ownerId: "5", ownerName: "Alex Kim", orgId: "org-2", createdAt: "2025-09-01", updatedAt: "2025-12-01" },
  { id: "c22", firstName: "Priya", lastName: "Sharma", title: "CTO", accountId: "a12", accountName: "DataDriven Co", phone: "(555) 200-3000", email: "psharma@datadriven.com", mailingAddress: "200 Data Blvd, San Jose, CA 95101", department: "Engineering", ownerId: "6", ownerName: "Lisa Park", orgId: "org-2", createdAt: "2025-08-15", updatedAt: "2025-11-15" },
  // Org 3
  { id: "c23", firstName: "William", lastName: "Clarke", title: "Managing Director", accountId: "a13", accountName: "FinServ Partners", phone: "+44 20 7123 4567", email: "wclarke@finserv.co.uk", mailingAddress: "10 Downing St, London, UK", department: "Management", ownerId: "7", ownerName: "James Wilson", orgId: "org-3", createdAt: "2025-07-01", updatedAt: "2025-12-01" },
  { id: "c24", firstName: "Charlotte", lastName: "Reed", title: "Investment Analyst", accountId: "a14", accountName: "Capital Group", phone: "+44 20 7234 5678", email: "creed@capitalgroup.co.uk", mailingAddress: "1 Canary Wharf, London, UK", department: "Investments", ownerId: "8", ownerName: "Rachel Brown", orgId: "org-3", createdAt: "2025-06-15", updatedAt: "2025-11-15" },
];

// ── Accounts ──
export const accounts: Account[] = [
  { id: "a1", name: "Globex Corporation", industry: "Technology", type: "Customer", phone: "(555) 100-1000", website: "globex.com", billingAddress: "123 Main St, Springfield, IL 62701", description: "Major tech enterprise, 5000+ employees", employees: 5200, annualRevenue: 850000000, ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-01-10", updatedAt: "2025-12-01" },
  { id: "a2", name: "Initech", industry: "Software", type: "Customer", phone: "(555) 200-2000", website: "initech.com", billingAddress: "456 Oak Ave, Austin, TX 73301", description: "Mid-market software company focusing on ERP solutions", employees: 1200, annualRevenue: 280000000, ownerId: "2", ownerName: "Sarah Chen", orgId: "org-1", createdAt: "2025-02-15", updatedAt: "2025-11-20" },
  { id: "a3", name: "Umbrella Corp", industry: "Pharmaceutical", type: "Prospect", phone: "(555) 300-3000", website: "umbrella.com", billingAddress: "789 Pine Rd, Raccoon City, OH 44101", description: "Large pharmaceutical conglomerate", employees: 12000, annualRevenue: 3200000000, ownerId: "3", ownerName: "Mike Johnson", orgId: "org-1", createdAt: "2025-03-01", updatedAt: "2025-10-15" },
  { id: "a4", name: "Stark Industries", industry: "Manufacturing", type: "Customer", phone: "(555) 400-4000", website: "starkindustries.com", billingAddress: "1 Stark Tower, New York, NY 10001", description: "Leading manufacturer and defense contractor", employees: 45000, annualRevenue: 12000000000, ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-01-20", updatedAt: "2025-12-10" },
  { id: "a5", name: "Wayne Enterprises", industry: "Conglomerate", type: "Customer", phone: "(555) 500-5000", website: "wayneenterprises.com", billingAddress: "1007 Mountain Dr, Gotham, NJ 07001", description: "Multi-industry conglomerate with tech and defense divisions", employees: 32000, annualRevenue: 7500000000, ownerId: "2", ownerName: "Sarah Chen", orgId: "org-1", createdAt: "2025-02-28", updatedAt: "2025-11-30" },
  { id: "a6", name: "Acme Solutions", industry: "Consulting", type: "Partner", phone: "(555) 600-6000", website: "acmesolutions.com", billingAddress: "321 Elm St, San Francisco, CA 94102", description: "Boutique consulting firm specializing in digital transformation", employees: 450, annualRevenue: 85000000, ownerId: "3", ownerName: "Mike Johnson", orgId: "org-1", createdAt: "2025-04-10", updatedAt: "2025-10-30" },
  { id: "a7", name: "Cyberdyne Systems", industry: "Technology", type: "Prospect", phone: "(555) 700-7000", website: "cyberdyne.com", billingAddress: "18144 El Camino Real, Sunnyvale, CA 94087", description: "AI and robotics research company", employees: 800, annualRevenue: 120000000, ownerId: "4", ownerName: "Emily Davis", orgId: "org-1", createdAt: "2025-05-15", updatedAt: "2025-11-10" },
  { id: "a8", name: "Soylent Corp", industry: "Food & Beverage", type: "Customer", phone: "(555) 800-8000", website: "soylentcorp.com", billingAddress: "500 Broadway, New York, NY 10012", description: "Innovative food technology company", employees: 2100, annualRevenue: 450000000, ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-03-20", updatedAt: "2025-12-05" },
  { id: "a9", name: "Weyland-Yutani", industry: "Aerospace", type: "Prospect", phone: "(555) 900-9000", website: "weyland-yutani.com", billingAddress: "900 Industrial Pkwy, Houston, TX 77001", description: "Aerospace and defense corporation", employees: 18000, annualRevenue: 5600000000, ownerId: "2", ownerName: "Sarah Chen", orgId: "org-1", createdAt: "2025-06-01", updatedAt: "2025-11-22" },
  { id: "a10", name: "Oscorp Industries", industry: "Biotech", type: "Customer", phone: "(555) 000-1000", website: "oscorp.com", billingAddress: "200 Park Ave, New York, NY 10166", description: "Biotech leader in gene therapy and materials science", employees: 6500, annualRevenue: 1800000000, ownerId: "3", ownerName: "Mike Johnson", orgId: "org-1", createdAt: "2025-04-25", updatedAt: "2025-10-28" },
  // Org 2
  { id: "a11", name: "CloudFirst", industry: "Cloud Computing", type: "Customer", phone: "(555) 100-2001", website: "cloudfirst.io", billingAddress: "100 Cloud Way, Seattle, WA 98101", description: "Cloud infrastructure provider", employees: 300, annualRevenue: 45000000, ownerId: "5", ownerName: "Alex Kim", orgId: "org-2", createdAt: "2025-03-10", updatedAt: "2025-12-01" },
  { id: "a12", name: "DataDriven Co", industry: "Analytics", type: "Prospect", phone: "(555) 200-3001", website: "datadriven.co", billingAddress: "200 Data Blvd, San Jose, CA 95101", description: "Data analytics and AI platform", employees: 150, annualRevenue: 22000000, ownerId: "6", ownerName: "Lisa Park", orgId: "org-2", createdAt: "2025-05-20", updatedAt: "2025-11-15" },
  // Org 3
  { id: "a13", name: "FinServ Partners", industry: "Financial Services", type: "Customer", phone: "+44 20 7100 1000", website: "finservpartners.co.uk", billingAddress: "10 Downing St, London, UK", description: "UK financial services advisory firm", employees: 800, annualRevenue: 120000000, ownerId: "7", ownerName: "James Wilson", orgId: "org-3", createdAt: "2025-02-01", updatedAt: "2025-12-01" },
  { id: "a14", name: "Capital Group", industry: "Investment", type: "Customer", phone: "+44 20 7200 2000", website: "capitalgroup.co.uk", billingAddress: "1 Canary Wharf, London, UK", description: "Investment management firm", employees: 2500, annualRevenue: 3500000000, ownerId: "8", ownerName: "Rachel Brown", orgId: "org-3", createdAt: "2025-01-15", updatedAt: "2025-11-15" },
];

// ── Deals ──
export const deals: Deal[] = [
  { id: "d1", name: "Globex Enterprise License", amount: 450000, stage: "Negotiation", closeDate: "2026-03-15", accountId: "a1", accountName: "Globex Corporation", contactId: "c1", contactName: "John Smith", probability: 75, ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-09-01", updatedAt: "2025-12-10" },
  { id: "d2", name: "Initech ERP Integration", amount: 280000, stage: "Proposal", closeDate: "2026-04-01", accountId: "a2", accountName: "Initech", contactId: "c2", contactName: "Jane Doe", probability: 50, ownerId: "2", ownerName: "Sarah Chen", orgId: "org-1", createdAt: "2025-08-15", updatedAt: "2025-11-28" },
  { id: "d3", name: "Umbrella Security Suite", amount: 180000, stage: "Qualification", closeDate: "2026-05-15", accountId: "a3", accountName: "Umbrella Corp", contactId: "c3", contactName: "Robert Brown", probability: 30, ownerId: "3", ownerName: "Mike Johnson", orgId: "org-1", createdAt: "2025-10-01", updatedAt: "2025-12-05" },
  { id: "d4", name: "Stark Analytics Platform", amount: 520000, stage: "Closed Won", closeDate: "2025-11-30", accountId: "a4", accountName: "Stark Industries", contactId: "c4", contactName: "Maria Garcia", probability: 100, ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-06-01", updatedAt: "2025-11-30" },
  { id: "d5", name: "Wayne Digital Transformation", amount: 380000, stage: "Negotiation", closeDate: "2026-02-28", accountId: "a5", accountName: "Wayne Enterprises", contactId: "c5", contactName: "David Lee", probability: 80, ownerId: "2", ownerName: "Sarah Chen", orgId: "org-1", createdAt: "2025-07-20", updatedAt: "2025-12-12" },
  { id: "d6", name: "Acme Consulting Package", amount: 95000, stage: "Prospecting", closeDate: "2026-06-01", accountId: "a6", accountName: "Acme Solutions", contactId: "c9", contactName: "Michael Chen", probability: 15, ownerId: "3", ownerName: "Mike Johnson", orgId: "org-1", createdAt: "2025-11-01", updatedAt: "2025-12-01" },
  { id: "d7", name: "Cyberdyne AI Module", amount: 210000, stage: "Qualification", closeDate: "2026-04-15", accountId: "a7", accountName: "Cyberdyne Systems", contactId: "c10", contactName: "Sarah Johnson", probability: 25, ownerId: "4", ownerName: "Emily Davis", orgId: "org-1", createdAt: "2025-10-15", updatedAt: "2025-11-20" },
  { id: "d8", name: "Soylent Supply Chain", amount: 155000, stage: "Proposal", closeDate: "2026-03-30", accountId: "a8", accountName: "Soylent Corp", contactId: "c11", contactName: "Tom Anderson", probability: 45, ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-09-20", updatedAt: "2025-12-08" },
  { id: "d9", name: "Weyland Space Systems", amount: 490000, stage: "Prospecting", closeDate: "2026-07-01", accountId: "a9", accountName: "Weyland-Yutani", contactId: "c17", contactName: "Daniel Wright", probability: 10, ownerId: "2", ownerName: "Sarah Chen", orgId: "org-1", createdAt: "2025-11-10", updatedAt: "2025-12-01" },
  { id: "d10", name: "Oscorp Lab Management", amount: 320000, stage: "Closed Won", closeDate: "2025-10-15", accountId: "a10", accountName: "Oscorp Industries", contactId: "c20", contactName: "Sophie Turner", probability: 100, ownerId: "3", ownerName: "Mike Johnson", orgId: "org-1", createdAt: "2025-05-01", updatedAt: "2025-10-15" },
  { id: "d11", name: "Globex Cloud Migration", amount: 175000, stage: "Closed Lost", closeDate: "2025-09-30", accountId: "a1", accountName: "Globex Corporation", contactId: "c6", contactName: "Lisa Wang", probability: 0, ownerId: "4", ownerName: "Emily Davis", orgId: "org-1", createdAt: "2025-04-15", updatedAt: "2025-09-30" },
  { id: "d12", name: "Initech Mobile App", amount: 120000, stage: "Prospecting", closeDate: "2026-05-30", accountId: "a2", accountName: "Initech", contactId: "c7", contactName: "James Taylor", probability: 10, ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-12-01", updatedAt: "2025-12-10" },
  { id: "d13", name: "Stark Security Audit", amount: 85000, stage: "Closed Won", closeDate: "2025-08-20", accountId: "a4", accountName: "Stark Industries", contactId: "c12", contactName: "Amy Rodriguez", probability: 100, ownerId: "2", ownerName: "Sarah Chen", orgId: "org-1", createdAt: "2025-03-10", updatedAt: "2025-08-20" },
  { id: "d14", name: "Wayne CRM Implementation", amount: 260000, stage: "Proposal", closeDate: "2026-03-01", accountId: "a5", accountName: "Wayne Enterprises", contactId: "c13", contactName: "Kevin Patel", probability: 55, ownerId: "3", ownerName: "Mike Johnson", orgId: "org-1", createdAt: "2025-10-20", updatedAt: "2025-12-01" },
  { id: "d15", name: "Cyberdyne Robotics Platform", amount: 340000, stage: "Closed Lost", closeDate: "2025-11-15", accountId: "a7", accountName: "Cyberdyne Systems", contactId: "c15", contactName: "Brian Murphy", probability: 0, ownerId: "4", ownerName: "Emily Davis", orgId: "org-1", createdAt: "2025-06-15", updatedAt: "2025-11-15" },
  // Org 2
  { id: "d16", name: "CloudFirst Infrastructure Deal", amount: 125000, stage: "Negotiation", closeDate: "2026-03-01", accountId: "a11", accountName: "CloudFirst", contactId: "c21", contactName: "Alex Kim", probability: 70, ownerId: "5", ownerName: "Alex Kim", orgId: "org-2", createdAt: "2025-09-15", updatedAt: "2025-12-01" },
  { id: "d17", name: "DataDriven Analytics Suite", amount: 88000, stage: "Qualification", closeDate: "2026-04-15", accountId: "a12", accountName: "DataDriven Co", contactId: "c22", contactName: "Priya Sharma", probability: 35, ownerId: "6", ownerName: "Lisa Park", orgId: "org-2", createdAt: "2025-10-01", updatedAt: "2025-11-20" },
  // Org 3
  { id: "d18", name: "FinServ Compliance Platform", amount: 310000, stage: "Proposal", closeDate: "2026-02-15", accountId: "a13", accountName: "FinServ Partners", contactId: "c23", contactName: "William Clarke", probability: 60, ownerId: "7", ownerName: "James Wilson", orgId: "org-3", createdAt: "2025-08-01", updatedAt: "2025-12-01" },
];

// ── Activities ──
export const activities: Activity[] = [
  { id: "act1", type: "call", subject: "Discovery call with John Smith", description: "Discuss enterprise needs and budget timeline", status: "Done", dueDate: "2025-12-10", contactId: "c1", contactName: "John Smith", accountId: "a1", accountName: "Globex Corporation", ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-12-08", completedAt: "2025-12-10" },
  { id: "act2", type: "email", subject: "Send proposal to Jane Doe", description: "Follow up with ERP integration proposal document", status: "Done", dueDate: "2025-12-09", contactId: "c2", contactName: "Jane Doe", accountId: "a2", accountName: "Initech", ownerId: "2", ownerName: "Sarah Chen", orgId: "org-1", createdAt: "2025-12-07", completedAt: "2025-12-09" },
  { id: "act3", type: "meeting", subject: "Quarterly review with Stark Industries", description: "Review Q4 performance and plan for Q1", status: "To Do", dueDate: "2026-02-25", contactId: "c4", contactName: "Maria Garcia", accountId: "a4", accountName: "Stark Industries", ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-12-01" },
  { id: "act4", type: "task", subject: "Update Globex contract terms", description: "Revise pricing in the enterprise license agreement", status: "In Progress", dueDate: "2026-02-26", contactId: "c1", contactName: "John Smith", accountId: "a1", accountName: "Globex Corporation", ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-12-05" },
  { id: "act5", type: "call", subject: "Follow up with Robert Brown", description: "Check on security suite demo feedback", status: "To Do", dueDate: "2026-02-25", contactId: "c3", contactName: "Robert Brown", accountId: "a3", accountName: "Umbrella Corp", ownerId: "3", ownerName: "Mike Johnson", orgId: "org-1", createdAt: "2025-12-10" },
  { id: "act6", type: "email", subject: "Send pricing update to Wayne", description: "Updated pricing for digital transformation project", status: "Waiting", dueDate: "2026-02-24", contactId: "c5", contactName: "David Lee", accountId: "a5", accountName: "Wayne Enterprises", ownerId: "2", ownerName: "Sarah Chen", orgId: "org-1", createdAt: "2025-12-08" },
  { id: "act7", type: "meeting", subject: "Product demo for Cyberdyne", description: "Demo AI module capabilities", status: "To Do", dueDate: "2026-02-27", contactId: "c10", contactName: "Sarah Johnson", accountId: "a7", accountName: "Cyberdyne Systems", ownerId: "4", ownerName: "Emily Davis", orgId: "org-1", createdAt: "2025-12-12" },
  { id: "act8", type: "task", subject: "Prepare Soylent presentation", description: "Create supply chain management slides", status: "In Progress", dueDate: "2026-02-25", contactId: "c11", contactName: "Tom Anderson", accountId: "a8", accountName: "Soylent Corp", ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-12-09" },
  { id: "act9", type: "call", subject: "Cold call to Weyland-Yutani", description: "Initial outreach about space systems deal", status: "To Do", dueDate: "2026-02-26", contactId: "c17", contactName: "Daniel Wright", accountId: "a9", accountName: "Weyland-Yutani", ownerId: "2", ownerName: "Sarah Chen", orgId: "org-1", createdAt: "2025-12-11" },
  { id: "act10", type: "email", subject: "Contract renewal notice - Oscorp", description: "Send renewal reminder for lab management platform", status: "Done", dueDate: "2025-12-08", contactId: "c20", contactName: "Sophie Turner", accountId: "a10", accountName: "Oscorp Industries", ownerId: "3", ownerName: "Mike Johnson", orgId: "org-1", createdAt: "2025-12-06", completedAt: "2025-12-08" },
  { id: "act11", type: "meeting", subject: "Team sync - Pipeline review", description: "Weekly team meeting to review deal pipeline", status: "Done", dueDate: "2025-12-12", ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-12-10", completedAt: "2025-12-12" },
  { id: "act12", type: "task", subject: "Create case study for Stark deal", description: "Write case study on Stark Analytics Platform success", status: "To Do", dueDate: "2026-02-28", contactId: "c4", contactName: "Maria Garcia", accountId: "a4", accountName: "Stark Industries", ownerId: "4", ownerName: "Emily Davis", orgId: "org-1", createdAt: "2025-12-01" },
  { id: "act13", type: "call", subject: "Check in with Lisa Wang", description: "Monthly relationship call", status: "Waiting", dueDate: "2026-02-27", contactId: "c6", contactName: "Lisa Wang", accountId: "a1", accountName: "Globex Corporation", ownerId: "3", ownerName: "Mike Johnson", orgId: "org-1", createdAt: "2025-12-05" },
  { id: "act14", type: "email", subject: "Send onboarding docs to Acme", description: "New partner onboarding documentation", status: "To Do", dueDate: "2026-02-25", contactId: "c9", contactName: "Michael Chen", accountId: "a6", accountName: "Acme Solutions", ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-12-10" },
  { id: "act15", type: "meeting", subject: "Negotiation call with Globex", description: "Discuss final terms for enterprise license", status: "To Do", dueDate: "2026-02-26", contactId: "c1", contactName: "John Smith", accountId: "a1", accountName: "Globex Corporation", dealId: "d1", ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-12-12" },
  { id: "act16", type: "task", subject: "Update CRM records for Q4", description: "Ensure all Q4 activities are logged", status: "In Progress", dueDate: "2026-02-25", ownerId: "2", ownerName: "Sarah Chen", orgId: "org-1", createdAt: "2025-12-01" },
  { id: "act17", type: "call", subject: "Reference check - Kevin Patel", description: "Call reference for Wayne CRM implementation", status: "Done", dueDate: "2025-12-11", contactId: "c13", contactName: "Kevin Patel", accountId: "a5", accountName: "Wayne Enterprises", ownerId: "3", ownerName: "Mike Johnson", orgId: "org-1", createdAt: "2025-12-09", completedAt: "2025-12-11" },
  { id: "act18", type: "email", subject: "Follow up on demo feedback", description: "Follow up with Brian Murphy on robotics platform demo", status: "Done", dueDate: "2025-12-07", contactId: "c15", contactName: "Brian Murphy", accountId: "a7", accountName: "Cyberdyne Systems", ownerId: "4", ownerName: "Emily Davis", orgId: "org-1", createdAt: "2025-12-05", completedAt: "2025-12-07" },
  { id: "act19", type: "meeting", subject: "Strategy session with marketing", description: "Align on Q1 campaign strategy", status: "To Do", dueDate: "2026-02-28", ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-12-12" },
  { id: "act20", type: "task", subject: "Competitive analysis report", description: "Prepare competitive landscape report for leadership", status: "Waiting", dueDate: "2026-02-27", ownerId: "2", ownerName: "Sarah Chen", orgId: "org-1", createdAt: "2025-12-08" },
  { id: "act21", type: "call", subject: "Intro call with Nicole Kim", description: "Introduction call for Acme Solutions partnership", status: "To Do", dueDate: "2026-02-25", contactId: "c14", contactName: "Nicole Kim", accountId: "a6", accountName: "Acme Solutions", ownerId: "3", ownerName: "Mike Johnson", orgId: "org-1", createdAt: "2025-12-11" },
  { id: "act22", type: "email", subject: "Thank you note to Maria Garcia", description: "Thank you for closing Stark Analytics deal", status: "Done", dueDate: "2025-12-01", contactId: "c4", contactName: "Maria Garcia", accountId: "a4", accountName: "Stark Industries", ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-11-30", completedAt: "2025-12-01" },
  { id: "act23", type: "meeting", subject: "Budget planning for Q1", description: "Plan Q1 sales budget and targets", status: "In Progress", dueDate: "2026-02-26", ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-12-10" },
  { id: "act24", type: "task", subject: "Prepare Weyland proposal", description: "Draft initial proposal for space systems project", status: "To Do", dueDate: "2026-03-01", contactId: "c17", contactName: "Daniel Wright", accountId: "a9", accountName: "Weyland-Yutani", dealId: "d9", ownerId: "2", ownerName: "Sarah Chen", orgId: "org-1", createdAt: "2025-12-12" },
  { id: "act25", type: "call", subject: "Check in with Rachel Foster", description: "Discuss Soylent supply chain project status", status: "To Do", dueDate: "2026-02-26", contactId: "c16", contactName: "Rachel Foster", accountId: "a8", accountName: "Soylent Corp", ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-12-11" },
  { id: "act26", type: "email", subject: "Send meeting recap to Laura", description: "Recap of HR system discussion", status: "Waiting", dueDate: "2026-02-25", contactId: "c18", contactName: "Laura Martinez", accountId: "a10", accountName: "Oscorp Industries", ownerId: "3", ownerName: "Mike Johnson", orgId: "org-1", createdAt: "2025-12-09" },
  { id: "act27", type: "meeting", subject: "Contract review with legal", description: "Review Globex enterprise license contract with legal team", status: "To Do", dueDate: "2026-02-27", dealId: "d1", ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-12-12" },
  { id: "act28", type: "task", subject: "Submit expense report", description: "Submit Q4 travel and entertainment expenses", status: "To Do", dueDate: "2026-02-28", ownerId: "4", ownerName: "Emily Davis", orgId: "org-1", createdAt: "2025-12-10" },
  { id: "act29", type: "call", subject: "Close negotiation with David Lee", description: "Final price negotiation for Wayne digital transformation", status: "In Progress", dueDate: "2026-02-25", contactId: "c5", contactName: "David Lee", accountId: "a5", accountName: "Wayne Enterprises", dealId: "d5", ownerId: "2", ownerName: "Sarah Chen", orgId: "org-1", createdAt: "2025-12-12" },
  { id: "act30", type: "email", subject: "Invoice follow-up - Stark", description: "Follow up on outstanding Stark Analytics invoice", status: "To Do", dueDate: "2026-02-25", contactId: "c4", contactName: "Maria Garcia", accountId: "a4", accountName: "Stark Industries", ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-12-11" },
  // Org 2
  { id: "act31", type: "call", subject: "CloudFirst infrastructure review", status: "To Do", dueDate: "2026-02-25", contactId: "c21", contactName: "Alex Kim", accountId: "a11", accountName: "CloudFirst", ownerId: "5", ownerName: "Alex Kim", orgId: "org-2", createdAt: "2025-12-10" },
  { id: "act32", type: "email", subject: "DataDriven proposal follow-up", status: "In Progress", dueDate: "2026-02-26", contactId: "c22", contactName: "Priya Sharma", accountId: "a12", accountName: "DataDriven Co", ownerId: "6", ownerName: "Lisa Park", orgId: "org-2", createdAt: "2025-12-08" },
  // Org 3
  { id: "act33", type: "meeting", subject: "FinServ compliance review", status: "To Do", dueDate: "2026-02-27", contactId: "c23", contactName: "William Clarke", accountId: "a13", accountName: "FinServ Partners", ownerId: "7", ownerName: "James Wilson", orgId: "org-3", createdAt: "2025-12-05" },
  { id: "act34", type: "task", subject: "Capital Group investment report", status: "In Progress", dueDate: "2026-02-28", contactId: "c24", contactName: "Charlotte Reed", accountId: "a14", accountName: "Capital Group", ownerId: "8", ownerName: "Rachel Brown", orgId: "org-3", createdAt: "2025-12-01" },
];

// ── Leads ──
export const leads: Lead[] = [
  { id: "l1", firstName: "Tyler", lastName: "Brooks", company: "NextGen Software", title: "VP Sales", email: "tbrooks@nextgen.com", phone: "(555) 111-0001", status: "New", source: "Website", rating: "Hot", industry: "Technology", description: "Filled out demo request form", ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-12-10" },
  { id: "l2", firstName: "Amanda", lastName: "Stone", company: "PeakView Analytics", title: "Director of Ops", email: "astone@peakview.com", phone: "(555) 111-0002", status: "Contacted", source: "Trade Show", rating: "Warm", industry: "Analytics", description: "Met at SaaStr conference, interested in enterprise plan", ownerId: "2", ownerName: "Sarah Chen", orgId: "org-1", createdAt: "2025-12-08" },
  { id: "l3", firstName: "Ryan", lastName: "Cooper", company: "Zenith Media", title: "CMO", email: "rcooper@zenith.com", phone: "(555) 111-0003", status: "Qualified", source: "Referral", rating: "Hot", industry: "Media", description: "Referred by existing customer, ready for proposal", ownerId: "3", ownerName: "Mike Johnson", orgId: "org-1", createdAt: "2025-12-05" },
  { id: "l4", firstName: "Jessica", lastName: "Hall", company: "Vertex Engineering", title: "CTO", email: "jhall@vertex.com", phone: "(555) 111-0004", status: "New", source: "LinkedIn", rating: "Cold", industry: "Engineering", ownerId: "4", ownerName: "Emily Davis", orgId: "org-1", createdAt: "2025-12-12" },
  { id: "l5", firstName: "Marcus", lastName: "Williams", company: "Horizon Health", title: "COO", email: "mwilliams@horizon.com", phone: "(555) 111-0005", status: "Contacted", source: "Cold Call", rating: "Warm", industry: "Healthcare", description: "Interested but evaluating competitors", ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-12-01" },
  { id: "l6", firstName: "Samantha", lastName: "Park", company: "Elite Logistics", title: "Supply Chain Director", email: "spark@elite.com", phone: "(555) 111-0006", status: "Unqualified", source: "Website", rating: "Cold", industry: "Logistics", description: "Budget too small for our minimum deal size", ownerId: "2", ownerName: "Sarah Chen", orgId: "org-1", createdAt: "2025-11-28" },
  { id: "l7", firstName: "Derek", lastName: "Fox", company: "Apex Financial", title: "Head of IT", email: "dfox@apexfin.com", phone: "(555) 111-0007", status: "New", source: "Webinar", rating: "Warm", industry: "Finance", ownerId: "3", ownerName: "Mike Johnson", orgId: "org-1", createdAt: "2025-12-11" },
  { id: "l8", firstName: "Victoria", lastName: "Chen", company: "BlueSky Ventures", title: "Partner", email: "vchen@bluesky.com", phone: "(555) 111-0008", status: "Qualified", source: "Referral", rating: "Hot", industry: "Venture Capital", description: "Looking for portfolio company CRM solution", ownerId: "4", ownerName: "Emily Davis", orgId: "org-1", createdAt: "2025-12-03" },
  { id: "l9", firstName: "Patrick", lastName: "O'Brien", company: "Emerald Tech", title: "CEO", email: "pobrien@emerald.com", phone: "(555) 111-0009", status: "Contacted", source: "Email Campaign", rating: "Warm", industry: "Technology", ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-12-07" },
  { id: "l10", firstName: "Natalie", lastName: "Ross", company: "Summit Group", title: "VP Business Dev", email: "nross@summit.com", phone: "(555) 111-0010", status: "New", source: "Partner Referral", rating: "Hot", industry: "Consulting", description: "Urgent need - current CRM contract expiring", ownerId: "2", ownerName: "Sarah Chen", orgId: "org-1", createdAt: "2025-12-12" },
  // Org 2
  { id: "l11", firstName: "Jason", lastName: "Lee", company: "Nimbus Cloud", title: "CTO", email: "jlee@nimbus.io", phone: "(555) 222-0001", status: "New", source: "Website", rating: "Warm", industry: "Cloud Computing", ownerId: "5", ownerName: "Alex Kim", orgId: "org-2", createdAt: "2025-12-10" },
  // Org 3
  { id: "l12", firstName: "Oliver", lastName: "Thompson", company: "Sterling Bank", title: "MD", email: "othompson@sterling.co.uk", phone: "+44 20 7300 3000", status: "Qualified", source: "Referral", rating: "Hot", industry: "Banking", ownerId: "7", ownerName: "James Wilson", orgId: "org-3", createdAt: "2025-12-05" },
];

// ── Cases ──
export const cases: Case[] = [
  { id: "cs1", subject: "Login issues with SSO integration", status: "Working", priority: "High", description: "Customer unable to log in via SSO after recent update. Affecting multiple users at Globex.", resolution: undefined, contactId: "c1", contactName: "John Smith", accountId: "a1", accountName: "Globex Corporation", ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-12-10" },
  { id: "cs2", subject: "Data export formatting error", status: "New", priority: "Medium", description: "CSV exports have incorrect date formatting. Dates appear in wrong timezone.", contactId: "c2", contactName: "Jane Doe", accountId: "a2", accountName: "Initech", ownerId: "2", ownerName: "Sarah Chen", orgId: "org-1", createdAt: "2025-12-11" },
  { id: "cs3", subject: "API rate limiting too aggressive", status: "Escalated", priority: "High", description: "Customer hitting API rate limits during normal business operations. Integration breaking during peak hours.", contactId: "c4", contactName: "Maria Garcia", accountId: "a4", accountName: "Stark Industries", ownerId: "3", ownerName: "Mike Johnson", orgId: "org-1", createdAt: "2025-12-09" },
  { id: "cs4", subject: "Dashboard loading slowly", status: "Working", priority: "Low", description: "Analytics dashboard takes 15+ seconds to load for accounts with large datasets.", contactId: "c5", contactName: "David Lee", accountId: "a5", accountName: "Wayne Enterprises", ownerId: "4", ownerName: "Emily Davis", orgId: "org-1", createdAt: "2025-12-08" },
  { id: "cs5", subject: "Missing email notifications", status: "Closed", priority: "Medium", description: "Customer not receiving automated email notifications for new leads.", resolution: "Fixed email service configuration. Notifications now sending correctly.", contactId: "c11", contactName: "Tom Anderson", accountId: "a8", accountName: "Soylent Corp", ownerId: "1", ownerName: "Demo User", orgId: "org-1", createdAt: "2025-12-05", closedAt: "2025-12-08" },
  { id: "cs6", subject: "Custom field validation broken", status: "New", priority: "Low", description: "Custom picklist fields not validating input correctly on the contact form.", contactId: "c9", contactName: "Michael Chen", accountId: "a6", accountName: "Acme Solutions", ownerId: "2", ownerName: "Sarah Chen", orgId: "org-1", createdAt: "2025-12-12" },
  { id: "cs7", subject: "Report generation timeout", status: "Working", priority: "High", description: "Large report generation times out after 60 seconds. Customer needs reports for 50K+ records.", contactId: "c20", contactName: "Sophie Turner", accountId: "a10", accountName: "Oscorp Industries", ownerId: "3", ownerName: "Mike Johnson", orgId: "org-1", createdAt: "2025-12-07" },
  // Org 2
  { id: "cs8", subject: "Integration sync failure", status: "New", priority: "Medium", description: "Google Calendar integration failing to sync events.", contactId: "c21", contactName: "Alex Kim", accountId: "a11", accountName: "CloudFirst", ownerId: "5", ownerName: "Alex Kim", orgId: "org-2", createdAt: "2025-12-10" },
];

// ── Call Scripts ──
export const callScripts: CallScript[] = [
  {
    id: "scr1", name: "Cold Call - Enterprise", description: "Standard cold call script for enterprise prospects",
    blocks: [
      { id: "sb1", title: "Intro", content: "Hi [Name], this is [Your Name] from Axia. I'm reaching out because we help companies like [Company] streamline their sales operations. Do you have 2 minutes?", notes: "Be friendly and confident", branchingHint: "If busy → schedule callback" },
      { id: "sb2", title: "Discovery", content: "What CRM are you currently using? What are the biggest challenges your sales team faces? How do you track your pipeline today?", notes: "Listen actively, take notes", branchingHint: "If happy with current → ask about pain points" },
      { id: "sb3", title: "Pitch", content: "Axia helps teams like yours increase win rates by 35% with AI-powered insights, automated follow-ups, and real-time pipeline visibility. We integrate with all your existing tools.", notes: "Focus on their specific pain points" },
      { id: "sb4", title: "Objection Handling", content: "I understand the concern about switching costs. Our migration team handles everything, and most customers are fully onboarded within 2 weeks. We also offer a 90-day satisfaction guarantee.", notes: "Address specific objections" },
      { id: "sb5", title: "Close", content: "Would you be open to a 15-minute demo this week to see how Axia could work for [Company]? I have availability on [Day] at [Time].", notes: "Always suggest specific times", branchingHint: "If yes → book meeting. If not now → schedule follow-up" },
    ],
    orgId: "org-1", createdAt: "2025-10-01", updatedAt: "2025-12-01",
  },
  {
    id: "scr2", name: "Follow-Up - Demo Attended", description: "Follow-up script for prospects who attended a demo",
    blocks: [
      { id: "sb6", title: "Intro", content: "Hi [Name], this is [Your Name] from Axia. Thanks again for attending the demo last [day]. I wanted to follow up and see if you had any questions.", notes: "Reference specific demo highlights" },
      { id: "sb7", title: "Discovery", content: "Which features resonated most with your team? Are there any concerns or questions that came up after the demo?", notes: "Note their priorities for proposal" },
      { id: "sb8", title: "Pitch", content: "Based on what you shared, I've put together a custom proposal that focuses on [their priorities]. I'd love to walk you through it.", notes: "Personalize to their needs" },
      { id: "sb9", title: "Close", content: "Can we schedule a call with your team to review the proposal? I want to make sure everyone's questions are addressed. How does [Day] look?", notes: "Try to include decision makers" },
    ],
    orgId: "org-1", createdAt: "2025-10-15", updatedAt: "2025-12-05",
  },
  {
    id: "scr3", name: "Renewal Call", description: "Script for customer renewal conversations",
    blocks: [
      { id: "sb10", title: "Intro", content: "Hi [Name], this is [Your Name] from Axia. I'm calling about your upcoming renewal on [date]. How has your experience been?", notes: "Start positive" },
      { id: "sb11", title: "Discovery", content: "What features has your team found most valuable? Are there any areas where you'd like to see improvement?", notes: "Document feedback" },
      { id: "sb12", title: "Pitch", content: "We've added several new features since your last renewal, including [features]. I'd also like to discuss our new tier options that might be a better fit.", notes: "Highlight new value" },
      { id: "sb13", title: "Close", content: "Based on our conversation, I'll send over the renewal proposal with the updated pricing. Can I count on getting this wrapped up by [date]?", notes: "Create urgency with expiration" },
    ],
    orgId: "org-1", createdAt: "2025-11-01", updatedAt: "2025-12-10",
  },
  {
    id: "scr4", name: "Upsell - Premium Features", description: "Script for upselling premium features to existing customers",
    blocks: [
      { id: "sb14", title: "Intro", content: "Hi [Name], I noticed your team has been using Axia extensively — your usage is up 40% this quarter! I wanted to share some ways to get even more value.", notes: "Lead with data" },
      { id: "sb15", title: "Discovery", content: "How is the team finding the current workflow? Are there any bottlenecks or manual processes you'd like to automate?", notes: "Listen for upsell opportunities" },
      { id: "sb16", title: "Pitch", content: "Our premium tier includes AI-powered deal scoring, advanced analytics, and automated workflow builders. Based on your usage, I estimate it could save your team 10+ hours per week.", notes: "Quantify the value" },
      { id: "sb17", title: "Close", content: "I can set up a trial of the premium features for your team this week. Would that be helpful?", notes: "Low commitment ask" },
    ],
    orgId: "org-1", createdAt: "2025-11-15", updatedAt: "2025-12-08",
  },
  {
    id: "scr5", name: "Win-Back Campaign", description: "Script for re-engaging churned customers",
    blocks: [
      { id: "sb18", title: "Intro", content: "Hi [Name], this is [Your Name] from Axia. It's been a while since we last spoke. I wanted to reach out because we've made some significant improvements since you last used the platform.", notes: "Be humble and genuine" },
      { id: "sb19", title: "Discovery", content: "I'd love to understand what led to the decision to move away from Axia. What are you using now, and how has that been working?", notes: "Don't be defensive" },
      { id: "sb20", title: "Pitch", content: "We've completely revamped [area they had issues with]. We also now offer [new features]. Many of our returning customers have seen [metric] improvement.", notes: "Address their specific reasons for leaving" },
      { id: "sb21", title: "Close", content: "Would you be open to a quick 10-minute walkthrough of what's changed? We're also offering a special returning customer pricing. No pressure at all.", notes: "Low pressure, special offer" },
    ],
    orgId: "org-1", createdAt: "2025-12-01", updatedAt: "2025-12-12",
  },
];

// ── Campaigns ──
export const campaigns: Campaign[] = [
  { id: "camp1", name: "Q1 Product Launch", status: "Planned", type: "Email", startDate: "2026-01-15", endDate: "2026-02-28", budget: 25000, responses: 0, description: "Email campaign for new product launch", orgId: "org-1", createdAt: "2025-12-01" },
  { id: "camp2", name: "SaaStr Conference 2025", status: "Completed", type: "Event", startDate: "2025-09-10", endDate: "2025-09-12", budget: 50000, actualCost: 47500, responses: 342, description: "Annual SaaStr conference booth and speaking slot", orgId: "org-1", createdAt: "2025-06-01" },
  { id: "camp3", name: "Winter Webinar Series", status: "Active", type: "Webinar", startDate: "2025-11-01", endDate: "2026-01-31", budget: 8000, actualCost: 3200, responses: 156, description: "Monthly webinar series on sales best practices", orgId: "org-1", createdAt: "2025-10-15" },
  { id: "camp4", name: "LinkedIn Ads - Enterprise", status: "Active", type: "Digital Ads", startDate: "2025-10-01", endDate: "2026-03-31", budget: 35000, actualCost: 18500, responses: 89, description: "LinkedIn advertising targeting enterprise buyers", orgId: "org-1", createdAt: "2025-09-20" },
  { id: "camp5", name: "Customer Referral Program", status: "Active", type: "Referral", startDate: "2025-07-01", endDate: "2026-06-30", budget: 15000, actualCost: 8200, responses: 28, description: "Incentivized referral program for existing customers", orgId: "org-1", createdAt: "2025-06-15" },
];

// ── Products ──
export const products: Product[] = [
  { id: "p1", name: "Axia CRM Starter", code: "AX-START", description: "Basic CRM for small teams. Includes contact management, deal tracking, and basic reporting.", price: 29, family: "CRM", isActive: true, pricingTiers: [{ minQty: 1, price: 29 }, { minQty: 10, price: 25 }, { minQty: 50, price: 20 }], orgId: "org-1", createdAt: "2025-01-01" },
  { id: "p2", name: "Axia CRM Professional", code: "AX-PRO", description: "Advanced CRM with automation, AI insights, and custom reporting. Includes power dialer.", price: 79, family: "CRM", isActive: true, pricingTiers: [{ minQty: 1, price: 79 }, { minQty: 10, price: 69 }, { minQty: 50, price: 55 }], orgId: "org-1", createdAt: "2025-01-01" },
  { id: "p3", name: "Axia CRM Enterprise", code: "AX-ENT", description: "Full-featured CRM with unlimited customization, dedicated support, and multi-org management.", price: 149, family: "CRM", isActive: true, pricingTiers: [{ minQty: 1, price: 149 }, { minQty: 10, price: 129 }, { minQty: 50, price: 99 }], orgId: "org-1", createdAt: "2025-01-01" },
  { id: "p4", name: "Power Dialer Add-On", code: "AX-DIAL", description: "Add power dialer functionality to any plan. Includes call recording, scripts, and analytics.", price: 35, family: "Add-Ons", isActive: true, pricingTiers: [{ minQty: 1, price: 35 }, { minQty: 10, price: 30 }], orgId: "org-1", createdAt: "2025-03-01" },
  { id: "p5", name: "Marketing Suite", code: "AX-MKT", description: "Email campaigns, lead scoring, and marketing automation. Integrates with CRM.", price: 49, family: "Marketing", isActive: true, pricingTiers: [{ minQty: 1, price: 49 }, { minQty: 10, price: 42 }], orgId: "org-1", createdAt: "2025-04-01" },
  { id: "p6", name: "Analytics Pro", code: "AX-ANALYTICS", description: "Advanced reporting and analytics dashboards with AI-powered insights.", price: 25, family: "Add-Ons", isActive: true, orgId: "org-1", createdAt: "2025-05-01" },
  { id: "p7", name: "Service Cloud", code: "AX-SVC", description: "Case management, knowledge base, and customer service tools.", price: 59, family: "Service", isActive: true, pricingTiers: [{ minQty: 1, price: 59 }, { minQty: 10, price: 49 }], orgId: "org-1", createdAt: "2025-02-01" },
  { id: "p8", name: "Legacy Basic (Deprecated)", code: "AX-LEGACY", description: "Previous generation CRM. No longer sold to new customers.", price: 19, family: "CRM", isActive: false, orgId: "org-1", createdAt: "2024-01-01" },
];

// ── Integrations ──
export const integrations: Integration[] = [
  { id: "int1", name: "Google Workspace", type: "google", enabled: true, orgId: "org-1" },
  { id: "int2", name: "Microsoft 365", type: "microsoft", enabled: false, orgId: "org-1" },
  { id: "int3", name: "Slack", type: "slack", enabled: true, orgId: "org-1" },
];
